export const ManageOptionActionType = {
    ADD_OPTION: 'ADD_OPTION',
    DELETE_OPTION: 'DELETE_OPTION',
    SHOW_ADD_OPTION_MODAL: 'SHOW_ADD_OPTION_MODAL',
    HIDE_ADD_OPTION_MODAL: 'HIDE_ADD_OPTION_MODAL',
    LOAD_OPTIONS: 'LOAD_OPTIONS',
    ADD_OPTION_SUCCESS: 'ADD_OPTION_SUCCESS',
    ADD_OPTION_FAIL: 'ADD_OPTION_FAIL',
    ADD_OPTION_ONCHANGE: 'ADD_OPTION_ONCHANGE',
    ADD_OPTION_VALIDATE: 'ADD_OPTION_VALIDATE'
};

