export const OptionGridActionType = {
    LOAD_OPTIONS: 'LOAD_OPTIONS',
    NO_RECORD_FOUND: 'NO_RECORD_FOUND',
    GET_OPTIONS_SUCCESS: 'GET_OPTIONS_SUCCESS',
    TAB_CHANGE: 'TAB_CHANGE',
    SHOW_ADD_OPTION_BUTTON: 'SHOW_ADD_OPTION_BUTTON',
    HIDE_ADD_OPTION_BUTTON: 'HIDE_ADD_OPTION_BUTTON',
    ADD_OPTION: 'ADD_OPTION',
    DELETE_OPTION: 'DELETE_OPTION',
    SHOW_ADD_OPTION_MODAL: 'SHOW_ADD_OPTION_MODAL',
    HIDE_ADD_OPTION_MODAL: 'HIDE_ADD_OPTION_MODAL',
    LOAD_OPTIONS: 'LOAD_OPTIONS',
    ADD_OPTION_SUCCESS: 'ADD_OPTION_SUCCESS',
    ADD_OPTION_FAIL: 'ADD_OPTION_FAIL',
    ADD_OPTION_ONCHANGE: 'ADD_OPTION_ONCHANGE',
    ADD_OPTION_VALIDATE: 'ADD_OPTION_VALIDATE',
    INVALID_ADD_OPTION: 'INVALID_ADD_OPTION'
};